### ISSUE TITLE
Замечание 1 - Юзабилити

### ISSUE THREAD

**Issue by ilyaashapatov** [Gozonishe/pizzaFabrikaEmployeeList#1]
Есть паттерны у полей ввода, но маски для ввода нет, или даже хотя бы плейсхолдера.
Еще можно использовать type у полей ввода - date и phone, это упростило бы ввод для пользователя.

https://github.com/Gozonishe/pizzaFabrikaEmployeeList/blob/43ad7822e65a231e0f74ec4d0a2b6b6e3c3c977e/src/components/NewEmpoyeeForm/NewEmployeeForm.js#L65

**Comment by Gozonishe** [comment]
fixed
![image](https://user-images.githubusercontent.com/42415404/57982274-d1a68d80-7a4b-11e9-86a2-ec5daa85a52a.png)
