### ISSUE TITLE
Замечание 2 - Ошибки

### ISSUE THREAD

**Issue by ilyaashapatov** [Gozonishe/pizzaFabrikaEmployeeList#2]
Такие ошибки тоже не желательны в тестовом задании.
![image](https://user-images.githubusercontent.com/1915906/57675345-66635280-762a-11e9-95aa-ac5958615822.png)

https://github.com/Gozonishe/pizzaFabrikaEmployeeList/blob/43ad7822e65a231e0f74ec4d0a2b6b6e3c3c977e/src/components/EditableTable/EditableTable.js#L137

**Comment by Gozonishe** [comment]
fixed
![image](https://user-images.githubusercontent.com/42415404/57800919-3cf61400-775b-11e9-9a7b-b58dd5f403d5.png)
