### ISSUE TITLE
Замечание 3 - Ошибки

### ISSUE THREAD

**Issue by ilyaashapatov** [Gozonishe/pizzaFabrikaEmployeeList#3]
В этом месте тоже

![image](https://user-images.githubusercontent.com/1915906/57675491-db368c80-762a-11e9-84cf-643e8d1410d6.png)

https://github.com/Gozonishe/pizzaFabrikaEmployeeList/blob/43ad7822e65a231e0f74ec4d0a2b6b6e3c3c977e/src/components/EmployeeListPage/EmployeeListPage.js#L91

**Comment by Gozonishe** [comment]
fixed
привел теги в порядок
